version: '3.8'
services:
  app:
    image: reg.rconfig.com:8443/rconfig/rconfigv7docker
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./data/.env:/var/www/html/rconfig8/current/.env  # Mount the .env file from local disk to container
      - ./data/storage:/var/www/html/rconfig8/current/storage  # Mount app storage directory to host directory

  db:
    image: mariadb:latest
    env_file: ./data/.env  # Use env_file to specify environment variables for DB
    ports:
      - "3360:3306"
    volumes:
      - ./data/db_data:/var/lib/mysql  # Mount MySQL data to host directory
 
volumes:
  db_data:

networks:
  rconfig_network:


